#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------

----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.edn" ]]; then
    cp "${APP_DIR}/config.edn" "${CONFIG_DIR}/config.edn"
    find "${CONFIG_DIR}/config.edn" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
