#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------

----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.edn" ]] && [[ ! -f "${CONFIG_DIR}/config.toml" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/config.toml] file."
    cp "${APP_DIR}/config.toml" "${CONFIG_DIR}/config.toml"
    find "${CONFIG_DIR}/config.toml" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

if [[ -f "${CONFIG_DIR}/config.edn" ]] && [[ ! -f "${CONFIG_DIR}/config.toml" ]]; then
    log_wrn "Installing default [${CONFIG_DIR}/config.example.toml] file, for manual migration."
    log_wrn "Please migrate your configuration to [${CONFIG_DIR}/config.toml] file, as the [${CONFIG_DIR}/config.edn] file is deprecated."
    cp "${APP_DIR}/config.toml" "${CONFIG_DIR}/config.example.toml"
    find "${CONFIG_DIR}/config.example.toml" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
