#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------

----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.edn" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/config.edn] file."
    cp "${APP_DIR}/config.edn" "${CONFIG_DIR}/config.edn"
    find "${CONFIG_DIR}/config.edn" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
