#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/config.edn" ]]; then
    echo "Installing default \"config.edn\"..."
    cp "${APP_DIR}/config.edn" "${CONFIG_DIR}/config.edn"
    chown hotio:hotio "${CONFIG_DIR}/config.edn"
fi
